version: '3'

services:
  kazarinof_web:
    image: httpd:2.4-alpine
    container_name: kazarinoff_web
    volumes:
      - ${PWD}/notebooks/_build/html:/usr/local/apache2/htdocs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    restart: on-failure
    networks:
      - proxy_aug07


networks:
    proxy_aug07:
      external: true

