#######################################################################################
# Book settings
title: ""
logo: images/logo.png
author: Peter D. Kazarinoff, PhD
email: peter.kazarinoff@pcc.edu
description: >- # this means to ignore newlines until "baseurl:"
  A jupyter-book port of "Problem Solving with Python"
  [https://www.amazon.com/dp/1693405415](https://www.amazon.com/dp/1693405415)

execute:
  execute_notebooks: cache

exclude_patterns: ["*ipynb"]

html:
  home_page_in_navbar: false
  baseurl: https://jupyterbook.org/
