#######################################################################################
# Book settings
title: "PSWP"
logo: images/logo.png
author: Peter D. Kazarinoff, PhD
email: peter.kazarinoff@pcc.edu
description: >- # this means to ignore newlines until "baseurl:"
  A jupyter-book port of "Problem Solving with Python"
  [https://www.amazon.com/dp/1693405415](https://www.amazon.com/dp/1693405415)

execute:
  execute_notebooks: cache

exclude_patterns: ["*ipynb"]

repository:
  url: https://github.com/executablebooks/jupyter-book
  branch: master
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "jupyterlab" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: http://127.0.0.1:9500
  
html:
  home_page_in_navbar: false
  baseurl: http://127.0.0.1:8500

